# fly.toml app configuration file generated for safesync on 2023-10-14T21:01:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "safesync"
primary_region = "mia"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
