# fly.toml app configuration file generated for 2004 on 2023-07-16T19:24:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "2004"
primary_region = "bog"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
